<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="25692" started-at="2017-12-08T00:43:17Z" finished-at="2017-12-08T00:43:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="25692" started-at="2017-12-08T00:43:17Z" finished-at="2017-12-08T00:43:43Z">
      <class name="com.tutorial.rapid.Nice1.tests.SimpleTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tutorial.rapid.Nice1.tests.SimpleTest@46d56d67]" name="setUp" is-config="true" duration-ms="3595" started-at="2017-12-08T02:43:17Z" finished-at="2017-12-08T02:43:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="_POSITIVE_TEST_()[pri:0, instance:com.tutorial.rapid.Nice1.tests.SimpleTest@46d56d67]" name="_POSITIVE_TEST_" duration-ms="11056" started-at="2017-12-08T02:43:21Z" finished-at="2017-12-08T02:43:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _POSITIVE_TEST_ -->
        <test-method status="PASS" signature="_REFRESH_SEQUENCE_()[pri:1, instance:com.tutorial.rapid.Nice1.tests.SimpleTest@46d56d67]" name="_REFRESH_SEQUENCE_" duration-ms="5287" started-at="2017-12-08T02:43:32Z" finished-at="2017-12-08T02:43:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _REFRESH_SEQUENCE_ -->
        <test-method status="FAIL" signature="_NEGATIVE_TEST_()[pri:2, instance:com.tutorial.rapid.Nice1.tests.SimpleTest@46d56d67]" name="_NEGATIVE_TEST_" duration-ms="5515" started-at="2017-12-08T02:43:37Z" finished-at="2017-12-08T02:43:43Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Hey World!] but found [Hello World!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Hey World!] but found [Hello World!]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at com.tutorial.rapid.Nice1.tests.SimpleTest._NEGATIVE_TEST_(SimpleTest.java:92)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- _NEGATIVE_TEST_ -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tutorial.rapid.Nice1.tests.SimpleTest@46d56d67]" name="tearDown" is-config="true" duration-ms="200" started-at="2017-12-08T02:43:43Z" finished-at="2017-12-08T02:43:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tutorial.rapid.Nice1.tests.SimpleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
